# -*- coding: utf-8 -*-
"""baseia_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MvvY-vsdEp0ti3PqKqeUIniSnTrfW7yg
"""

def soma(x, y):
  return x+y

def funcao_tola(string): #uma função equivalente ao tipo de retorno void do c++
  if (len(string) > 10):
    print('eita string longa...')
  elif (len(string) > 3 and len(string) <= 10):
    print('mais ou menos')
  else:
    print('agora eu aceito')

z = soma(2,3)
print(z)

funcao_tola('euestounotecinfoemprogramaia')

aluno = {
    'nome':'joaquim nabuco',
    'idade': 21,
    'endereco': 'rua das amoras, 23, macaiba',
}

aluno = {
  'matricula': [
      '123',
      '234',
      '567'
  ],
  'nome': ['joao','maria','pedro'],
  'idade': [16, 15, 18],
  'cpf': ['025', '111', '021']
}

#quais sao as colunas (chaves) do dict aluno
print(aluno.keys())
print(aluno.values())

import pandas as pd
df_aluno = pd.DataFrame(data=aluno)
df_aluno.head()

df_docentes = pd.read_csv('/content/docentes.csv', sep=';')
df_docentes.head(5)

df_docentes.tail(10)

df_docentes.shape

df_docentes.columns

#print(df_docentes[df_docentes['nome'] == 'JOSENALDE BARBOSA DE OLIVEIRA'])
pattern = r'^JOSENALDE'
pattern = r'(?i)^josenalde'
print(df_docentes[df_docentes['nome'].str.contains(pattern)])